/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2024-07-26 05:37:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.View;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;

public final class Contacts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1714931401585L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/Downloads/AP%20CW%202/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MediaTech/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425957970000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Orders</title>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://unpkg.com/boxicons@latest/css/boxicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/CSS/navbar.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/CSS/AddProduct.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Mochiy+Pop+One&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css\" integrity=\"sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".table_tag{\r\n");
      out.write("\t\r\n");
      out.write("\tmargin:50px 0 0 0;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("}\r\n");
      out.write(".product-table {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-table th,\r\n");
      out.write(".product-table td {\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    border-bottom: 1px solid #ddd; /* Border color */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-table th {\r\n");
      out.write("    background-color: #039164; /* Header background color */\r\n");
      out.write("    color: white; /* Header text color */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-table tr:nth-child(even) {\r\n");
      out.write("    background-color: #f2f2f2; /* Even row background color */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-table tr:hover {\r\n");
      out.write("    background-color: #ddd; /* Hover row background color */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body> \r\n");
      out.write("\t<header>\r\n");
      out.write("    <span class=\"logo\" onclick=\"navigateTo('./')\">MediaTech</span>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tconst navigateTo = (path) => {\r\n");
      out.write("\t\t\t\twindow.location.href = path;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("    <div class=\"center\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin-page\">Orders</a>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manageusers\">Users</a>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/AddProduct.jsp\">Add Product</a>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manageproducts\">Products</a>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view-contacts\">Contacts</a>\r\n");
      out.write("  </div>\r\n");
      out.write("    <div class=\"right\">\r\n");
      out.write("    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search\" class=\"search-bar\">\r\n");
      out.write("            <input type=\"text\" name = \"item-name\" class=\"search-field\" placeholder=\"Search this Website\" onclick=\"searchClicked()\">\r\n");
      out.write("            <input type=\"submit\" id=\"search\">\r\n");
      out.write("            <label for=\"search\"><i class='bx bx-search-alt-2'></i></label>\r\n");
      out.write("        </form>\r\n");
      out.write("        <script>\r\n");
      out.write("          const searchClicked = ()=>{\r\n");
      out.write("            document.querySelector(\".search-result\").style.top=\"70px\";\r\n");
      out.write("            document.querySelector(\".search-result\").style.opacity=\"1\";\r\n");
      out.write("          }\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("      const select = document.querySelector(\".dropbtn\")\r\n");
      out.write("      const option = document.querySelector(\".dropdown-content\")\r\n");
      out.write("            \r\n");
      out.write("      select.addEventListener(\"mouseenter\", ()=>{\r\n");
      out.write("        option.style.display = \"block\";\r\n");
      out.write("        option.style.top=\"80px\";\r\n");
      out.write("        option.style.opacity = \"1\";\r\n");
      out.write("      })\r\n");
      out.write("      option.addEventListener(\"mouseleave\", ()=>{\r\n");
      out.write("        option.style.top=\"-20%\";\r\n");
      out.write("        option.style.opacity = \"0\";\r\n");
      out.write("      })\r\n");
      out.write("  </script>\r\n");
      out.write("        <div class=\"icons\">\r\n");
      out.write("            <div class=\"cart\" onclick=\"cartClicked()\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/Images/shopping-cart.png\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"profile\" onclick=\"profileClicked()\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/Images/user.png\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"profile-section\">\r\n");
      out.write("      <div class=\"top\">\r\n");
      out.write("            <h1>User Profile</h1>\r\n");
      out.write("            <i class='bx bx-x' onclick=\"profileClicked()\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("      ");
 String email = null;
      if(session.getAttribute("loggedInId") == null){ 
      
      out.write("\r\n");
      out.write("          <div class=\"middle\">\r\n");
      out.write("              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/AdminLogin.jsp\">Login as Admin</a>\r\n");
      out.write("              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/Login.jsp\">Login as User</a>\r\n");
      out.write("      ");
} else{
        email = session.getAttribute("loggedInId").toString();
      
      out.write("\r\n");
      out.write("        <h1 class=\"intro\">You are Logged In as ");
      out.print( email );
      out.write("</h1>\r\n");
      out.write("        ");
if(session.getAttribute("adminEmail") != null){
      out.write("\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin-page\" class=\"admin-btn\">Admin Page</a><br/>\r\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"admin-btn\">Return to Home</a><br/>\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
if(session.getAttribute("adminEmail") == null && session.getAttribute("loggedInId") != null){
      out.write("\r\n");
      out.write("           <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/editProfile?email=");
      out.print(email);
      out.write("\" class=\"edit-profile-btn\">Edit Profile</a><br/>\r\n");
      out.write("\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"logout-profile-btn\">Log Out</a>\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"cart-section\">\r\n");
      out.write("      <div class=\"top\">\r\n");
      out.write("            <h1>Cart</h1>\r\n");
      out.write("            <i class='bx bx-x' onclick=\"profileClicked()\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("      <div class=\"middle\" id=\"middle\">\r\n");
      out.write("    \r\n");
      out.write("        </div>\r\n");
      out.write("      <div class=\"lower\">\r\n");
      out.write("        <span><p class=\"index\">Total Price: </p><p class=\"total-price\"></p></span>\r\n");
      out.write("        <a href=\"\" id = \"order\" onclick=\"clicked()\">Order Now!</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        const profileClicked = () =>{\r\n");
      out.write("            const btn = document.querySelector(\".profile\")\r\n");
      out.write("            const mainDiv = document.querySelector(\".profile-section\")\r\n");
      out.write("            const cross = document.querySelector(\".profile-section .top i\")\r\n");
      out.write("            btn.addEventListener(\"click\", ()=>{\r\n");
      out.write("                mainDiv.classList.add(\"active\");\r\n");
      out.write("            })\r\n");
      out.write("            cross.addEventListener(\"click\", ()=>{\r\n");
      out.write("                mainDiv.classList.remove(\"active\");\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        const cartClicked = () =>{\r\n");
      out.write("          ");
if(session.getAttribute("adminEmail") == null && session.getAttribute("loggedInId") != null){ 
      out.write("\r\n");
      out.write("            const btn = document.querySelector(\".cart\")\r\n");
      out.write("            const mainDiv = document.querySelector(\".cart-section\")\r\n");
      out.write("            const cross = document.querySelector(\".cart-section .top i\")\r\n");
      out.write("            btn.addEventListener(\"click\", ()=>{\r\n");
      out.write("                mainDiv.classList.add(\"active\");\r\n");
      out.write("            })\r\n");
      out.write("            cross.addEventListener(\"click\", ()=>{\r\n");
      out.write("                mainDiv.classList.remove(\"active\");\r\n");
      out.write("            })\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            let cartDisplay = document.getElementById(\"middle\");\r\n");
      out.write("    let totalPriceDisp = document.querySelector(\".lower .total-price\");\r\n");
      out.write("            // Create an empty string to store the HTML content\r\n");
      out.write("            let cartHtml = \"\";\r\n");
      out.write("    let totalPrice = 0;\r\n");
      out.write("            // Loop through the cart object and generate HTML for each item\r\n");
      out.write("            cartItems.forEach((item) => {\r\n");
      out.write("              cartHtml += `\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("          <img src=/MediaTech/Images/`+item.image+`?v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/>\r\n");
      out.write("          <span>\r\n");
      out.write("            <h3>`+item.name+`</h3>\r\n");
      out.write("            <p>Price: Rs. `+item.price+`</p>\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("              `;\r\n");
      out.write("              totalPrice += parseInt(item.price);\r\n");
      out.write("            })\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            // Set the innerHTML of the cart display element to the generated HTML content\r\n");
      out.write("            cartDisplay.innerHTML = cartHtml;\r\n");
      out.write("            totalPriceDisp.innerText = totalPrice;\r\n");
      out.write("            ");
}else{
      out.write("\r\n");
      out.write("              alert(\"You should be logged in as user.\")\r\n");
      out.write("              window.location.href = \"./View/Login.jsp\"\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("</header>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <h2>Contacts</h2>\r\n");
      out.write("    <div class=\"table_tag\">\r\n");
      out.write("    <table class=\"product-table\">\r\n");
      out.write("          <tr>   \r\n");
      out.write("\t\t\t<th>Id</th>   \r\n");
      out.write("            <th>Contact</th>\r\n");
      out.write("            <th>Message</th>\r\n");
      out.write("          </tr>\r\n");
      out.write("          ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("\t</div>\r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /View/Contacts.jsp(214,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("st");
    // /View/Contacts.jsp(214,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/View/Contacts.jsp(214,10) '${contactList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${contactList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <tr>\r\n");
          out.write("              <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("              <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.contact}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("              <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${st.message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("            </tr>\r\n");
          out.write("          ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
